name: Mirror to Epitech

# Se déclenche à chaque push sur n'importe quelle branche
# C'est ce push qui va aussi envoyer le code vers le repo Epitech
on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v6

      - name: Mirror vers le repo Epitech
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:EpitechMscProPromo2028/T-DEV-600-MLN_1.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE }}
